# WARNING!! This is to build from source

version: "3.8"
services:
  liberaforms:
    build: .
    ports:
      - "5000:5000"
    environment:
        MONGODB_HOST: mongodb
        #MONGODB_DB: liberaforms
        #MONGODB_PORT: 27017
        #MONGODB_USERNAME: root
        #MONGODB_PASSWORD: rootpassword
    #volumes:
    #  - /app

  mongodb:
    image: mongo:latest
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
