# WARNING!! Configured for development env.
# WARNING!! This is to build liberaforms from source

version: "3.8"
services:
  liberaforms:
    build: .
    ports:
      - "5000:5000"
    environment:
        MEMCACHED_HOST: memcached
        #MEMCACHED_PORT: 11211
        MONGODB_HOST: mongodb
        MONGODB_DB: dev-liberaforms  #develop
        #MONGODB_PORT: 27017
        #MONGODB_USERNAME: root
        #MONGODB_PASSWORD: rootpassword
        FLASK_DEBUG: 1  #develop
    volumes:
      - liberaforms_instance:/app/instance
      - ./:/app #develop
    #command: /usr/local/bin/gunicorn -w 2 -b :5000 liberaforms:app
    command: flask run  #develop
  memcached:
    image: memcached:latest  
    ports:
      - "11211:11211"
  mongodb:
    image: mongo:latest
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  liberaforms_instance:
