"""empty message

Revision ID: 38395b979b79
Revises:
Create Date: 2021-07-11 13:02:04.933427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38395b979b79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('token', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_id'), 'invites', ['id'], unique=False)
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('scheme', sa.String(), nullable=False),
    sa.Column('siteName', sa.String(), nullable=False),
    sa.Column('defaultLanguage', sa.String(), nullable=False),
    sa.Column('primary_color', sa.String(), nullable=False),
    sa.Column('invitationOnly', sa.Boolean(), nullable=True),
    sa.Column('consentTexts', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=False),
    sa.Column('newUserConsentment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('smtpConfig', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('newuser_enableuploads', sa.Boolean(), nullable=False),
    sa.Column('mimetypes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_footer', sa.String(), nullable=True),
    sa.Column('blurb', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_id'), 'site', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('admin', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validatedEmail', sa.Boolean(), nullable=True),
    sa.Column('uploads_enabled', sa.Boolean(), nullable=False),
    sa.Column('token', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consentTexts', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('structure', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=False),
    sa.Column('fieldIndex', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=False),
    sa.Column('editors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.Column('sendConfirmation', sa.Boolean(), nullable=True),
    sa.Column('expiryConditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sharedAnswers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shared_notifications', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('restrictedAccess', sa.Boolean(), nullable=True),
    sa.Column('adminPreferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('introductionText', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('afterSubmitText', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expiredText', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consentTexts', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_forms_id'), 'forms', ['id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.String(), nullable=False),
    sa.Column('storage_name', sa.String(), nullable=False),
    sa.Column('local_filesystem', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('marked', sa.Boolean(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_id'), 'answers', ['id'], unique=False)
    op.create_table('form_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_logs_id'), 'form_logs', ['id'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('storage_name', sa.String(), nullable=False),
    sa.Column('local_filesystem', sa.Boolean(), nullable=True),
    sa.Column('file_size', sa.String(), nullable=False),
    sa.Column('encrypted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_form_logs_id'), table_name='form_logs')
    op.drop_table('form_logs')
    op.drop_index(op.f('ix_answers_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_forms_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_site_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_invites_id'), table_name='invites')
    op.drop_table('invites')
    # ### end Alembic commands ###


#op.execute("UPDATE site SET mimetypes = '{\"extensions\":[\"pdf\",\"png\",\"odt\"], \"mimetypes\":[\"application/pdf\",\"image/png\",\"application/vnd.oasis.opendocument.text\"]}'")
