"""empty message

Revision ID: 3d6ea469ff28
Revises: de85bba76a5d
Create Date: 2021-05-15 15:19:52.494202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6ea469ff28'
down_revision = 'de85bba76a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('attachmentsEnabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'attachmentsEnabled')
    # ### end Alembic commands ###
