"""empty message

Revision ID: 4df4248d2abe
Revises: 38395b979b79
Create Date: 2021-07-11 20:10:55.356770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import JSONB, ARRAY, TIMESTAMP
from sqlalchemy.orm.session import Session
from sqlalchemy.orm import declarative_base

# revision identifiers, used by Alembic.
revision = '4df4248d2abe'
down_revision = '38395b979b79'
branch_labels = None
depends_on = None

from bs4 import BeautifulSoup

def extract_text(html):
    soup = BeautifulSoup(html, features="lxml")
    return soup.get_text()

def truncate_text(text, truncate_at=155):
    text = text.replace('\n', ' ').strip(' ').replace('  ', ' ')
    if len(text) > truncate_at:
        text = f"{text[0:truncate_at-3]}..."
    return text

Base = declarative_base()

class Site(Base):
    __tablename__ = "site"
    id = sa.Column(sa.Integer, primary_key=True, index=True)
    created = sa.Column(TIMESTAMP, nullable=False)
    hostname = sa.Column(sa.String, nullable=False)
    port = sa.Column(sa.Integer, nullable=True)
    scheme = sa.Column(sa.String, nullable=False, default="http")
    siteName = sa.Column(sa.String, nullable=False)
    defaultLanguage = sa.Column(sa.String, nullable=False)
    primary_color = sa.Column(sa.String, nullable=False)
    invitationOnly = sa.Column(sa.Boolean, default=True)
    consentTexts = sa.Column(ARRAY(JSONB), nullable=False)
    newUserConsentment = sa.Column(JSONB, nullable=True)
    smtpConfig = sa.Column(JSONB, nullable=False)
    newuser_enableuploads = sa.Column(sa.Boolean, nullable=False, default=False)
    mimetypes = sa.Column(JSONB, nullable=False)
    email_footer = sa.Column(sa.String, nullable=True)
    blurb = sa.Column(JSONB, nullable=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fedi_auth', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('forms', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('forms', sa.Column('published_cnt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE forms SET published_cnt = 0")
    op.alter_column('forms', 'published_cnt', nullable=False)
    # update site.blurb with new 'short_text' key
    session = Session(bind=op.get_bind())
    site = session.query(Site).first()
    if site:
        text = extract_text(site.blurb['html']).strip('\n')
        text = truncate_text(text, truncate_at=155)
        new_blurb = {'html': site.blurb['html'],
                     'markdown': site.blurb['markdown'],
                     'short_text': text}
        site.blurb = new_blurb
        session.commit()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fedi_auth')
    op.drop_column('forms', 'published_cnt')
    op.drop_column('forms', 'thumbnail')
    # ### end Alembic commands ###
