"""empty message

Revision ID: 4f29f9a61403
Revises: 1a7e640ca3d0
Create Date: 2021-05-22 12:08:13.551332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f29f9a61403'
down_revision = '1a7e640ca3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('storage_name', sa.String(), nullable=False),
    sa.Column('local_filesystem', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_attachments_id'), 'answer_attachments', ['id'], unique=False)
    op.add_column('users', sa.Column('uploads_enabled', sa.Boolean(), nullable=True))
    op.add_column('site', sa.Column('newuser_uploadsdefault', sa.Boolean(), nullable=True))
    op.add_column('site', sa.Column('allowed_mimetypes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    op.execute("UPDATE users SET uploads_enabled = false")
    op.alter_column('users', 'uploads_enabled', nullable=False)

    op.execute("UPDATE site SET newuser_uploadsdefault = false")
    op.alter_column('site', 'newuser_uploadsdefault', nullable=False)

    op.execute("UPDATE site SET allowed_mimetypes = '{\"pdf\":\"application/pdf\",\"png\":\"image/png\", \"odt\":\"application/vnd.oasis.opendocument.text\"}'")
    op.alter_column('site', 'allowed_mimetypes', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'uploads_enabled')
    op.drop_column('site', 'allowed_mimetypes')
    op.drop_column('site', 'newuser_uploadsdefault')
    op.drop_index(op.f('ix_answer_attachments_id'), table_name='answer_attachments')
    op.drop_table('answer_attachments')
    # ### end Alembic commands ###
