"""empty message

Revision ID: 72a1e29354a8
Revises: d92d5d12bbba
Create Date: 2021-06-10 22:17:49.383915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a1e29354a8'
down_revision = 'd92d5d12bbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_size', sa.String(), nullable=False))
    op.add_column('attachments', sa.Column('encrypted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'encrypted')
    op.drop_column('attachments', 'file_size')
    # ### end Alembic commands ###
