"""empty message

Revision ID: 776095b3c447
Revises: 1a7e640ca3d0
Create Date: 2021-05-15 13:43:49.224376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776095b3c447'
down_revision = '1a7e640ca3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('storage_name', sa.String(), nullable=False),
    sa.Column('form_field_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_attachments_id'), 'answer_attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_attachments_id'), table_name='answer_attachments')
    op.drop_table('answer_attachments')
    # ### end Alembic commands ###
