"""empty message

Revision ID: 7a4ba63b5a9a
Revises: b06e1c00e0a5
Create Date: 2021-11-01 20:15:03.329870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4ba63b5a9a'
down_revision = 'b06e1c00e0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uploads_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE users SET uploads_limit = 26214400") # 250 MB
    op.alter_column('users', 'uploads_limit', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'uploads_limit')
    # ### end Alembic commands ###
