"""empty message

Revision ID: a6b48ae7220a
Revises: 09c0e8c80788
Create Date: 2021-05-19 02:15:22.593766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6b48ae7220a'
down_revision = '4f29f9a61403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('sharedNotifications', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'sharedNotifications')
    # ### end Alembic commands ###
