"""empty message

Revision ID: abc23f54d93c
Revises: 72a1e29354a8
Create Date: 2021-06-12 14:26:44.004035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abc23f54d93c'
down_revision = '72a1e29354a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('mimetypes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('site', 'allowed_mimetypes')
    op.execute("UPDATE site SET mimetypes = '{\"extensions\":[\"pdf\",\"png\",\"odt\"], \"mimetypes\":[\"application/pdf\",\"image/png\",\"application/vnd.oasis.opendocument.text\"]}'")
    op.alter_column('site', 'mimetypes', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('allowed_mimetypes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('site', 'mimetypes')
    # ### end Alembic commands ###
