"""empty message

Revision ID: aefffadd0252
Revises: 4df4248d2abe
Create Date: 2021-07-19 09:32:19.732803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefffadd0252'
down_revision = '4df4248d2abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('forms', sa.Column('published_cnt', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE forms SET published_cnt = 0")
    op.alter_column('forms', 'published_cnt', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'published_cnt')
    op.drop_column('forms', 'thumbnail')
    # ### end Alembic commands ###
