"""empty message

Revision ID: af57133c0586
Revises: 466961e4d03a
Create Date: 2021-07-10 12:02:39.068965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af57133c0586'
down_revision = '466961e4d03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###
    #op.alter_column('users', 'timezone', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
