"""empty message

Revision ID: b06e1c00e0a5
Revises: 64ba16324cef
Create Date: 2021-10-19 18:56:19.939571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b06e1c00e0a5'
down_revision = '64ba16324cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('edit_mode', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE forms SET edit_mode = '{}'")
    op.alter_column('forms', 'edit_mode', nullable=False)
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'edit_mode')
    # ### end Alembic commands ###
