"""empty message

Revision ID: b06e1c00e0a5
Revises: 64ba16324cef
Create Date: 2021-10-19 18:56:19.939571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm.session import Session
from sqlalchemy.orm import declarative_base
from sqlalchemy.ext.mutable import MutableDict
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision = 'b06e1c00e0a5'
down_revision = '64ba16324cef'
branch_labels = None
depends_on = None

Base = declarative_base()

class User(Base):
    __tablename__ = "users"
    id = sa.Column(sa.Integer, primary_key=True, index=True)
    preferences = sa.Column(MutableDict.as_mutable(JSONB), nullable=False)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('edit_mode', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE forms SET edit_mode = '{}'")
    op.alter_column('forms', 'edit_mode', nullable=False)
    # ### end Alembic commands ###
    session = Session(bind=op.get_bind())
    users = session.query(User).all()
    for user in users:
        user.preferences['show_edit_alert'] = True
    session.commit()
    session.close()

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'edit_mode')
    # ### end Alembic commands ###
    session = Session(bind=op.get_bind())
    users = session.query(User).all()
    for user in users:
        del user.preferences['show_edit_alert']
    session.commit()
    session.close()
