"""empty message

Revision ID: b59183d34016
Revises: 09c0e8c80788
Create Date: 2021-05-20 16:07:39.918079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59183d34016'
down_revision = '09c0e8c80788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_attachments', sa.Column('local_filesystem', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer_attachments', 'local_filesystem')
    # ### end Alembic commands ###
