"""empty message

Revision ID: d7bb6c452b8a
Revises: 4df4248d2abe
Create Date: 2021-07-19 09:00:52.351977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bb6c452b8a'
down_revision = '4df4248d2abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('short_desc', sa.String(), nullable=True))
    op.add_column('forms', sa.Column('published_cnt', sa.Integer(), nullable=True))
    op.add_column('site', sa.Column('short_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE forms SET published_cnt = 0")
    op.alter_column('forms', 'published_cnt', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'short_desc')
    op.drop_column('forms', 'published_cnt')
    op.drop_column('forms', 'short_desc')
    # ### end Alembic commands ###
