"""empty message

Revision ID: de85bba76a5d
Revises: 776095b3c447
Create Date: 2021-05-15 15:07:50.225738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de85bba76a5d'
down_revision = '776095b3c447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('attachmentsEnabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'attachmentsEnabled')
    # ### end Alembic commands ###
