"""empty message

Revision ID: f389c74ff484
Revises: d576500feaee
Create Date: 2021-05-21 23:56:28.238230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f389c74ff484'
down_revision = 'b59183d34016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('allowed_mimetypes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE site SET allowed_mimetypes = '{\"pdf\":\"application/pdf\",\"png\":\"image/png\", \"odt\":\"application/vnd.oasis.opendocument.text\"}'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'allowed_mimetypes')
    # ### end Alembic commands ###
